In [4]:
import os
import pandas as pd
#for loading and visualizing audio files
import librosa 
import librosa.display
import numpy as np
from bird import utils
import audio_spectrogram as rp
from audiofile_read import audiofile_read
import re
import glob
##Preprocessing functions
from bird import preprocessing as pr   
from bird import signal_processing as sp

In [16]:
root = './input_exp/converted/'

In [17]:
filenames = []
for root,dirs,files in os.walk(root):
    for file in files:
        if file.endswith(".wav"):
            filenames.append(os.path.join(root, file))
        
            

In [18]:
len(filenames)

1935

In [19]:
filenames

['./input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-102830_call.wav',
 './input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-14774_call.wav',
 './input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-20422_call.wav',
 './input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-63312_call.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103177_song.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103178_song.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103181_song.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-106265_song.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-112603_song.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-116198_song.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-118831_song.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Bea

In [7]:
filenames

['./trial_converted/input_exp/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-102830_call.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-14774_call.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-20422_call.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-63312_call.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_call\\Blue-collared-Zipper-3371_call.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103177_song.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103178_song.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103181_song.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-106265_song.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-112603_song.wav',
 './trial_converted/input_exp/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-116198_so

# This part deals with changing the stereo to mono channel if the files have already only one channel skip this to finally use the pr.preprocess_sound_file

In [20]:
from pydub import AudioSegment

In [21]:
for wav_file in filenames:
    sound = AudioSegment.from_wav(wav_file)
    sound = sound.set_channels(1)
    sound.export(wav_file[0:-4] + '_mono' + '.wav', format="wav")
    print(wav_file + ' is converted')

./input_exp/converted/Bent-Beak-Riffraff_call\Bent-Beak-Riffraff-102830_call.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_call\Bent-Beak-Riffraff-14774_call.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_call\Bent-Beak-Riffraff-20422_call.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_call\Bent-Beak-Riffraff-63312_call.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_song\Bent-Beak-Riffraff-103177_song.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_song\Bent-Beak-Riffraff-103178_song.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_song\Bent-Beak-Riffraff-103181_song.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_song\Bent-Beak-Riffraff-106265_song.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_song\Bent-Beak-Riffraff-112603_song.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_song\Bent-Beak-Riffraff-116198_song.wav is converted
./input_exp/converted/Bent-Beak-Riffraff_song\Bent-Beak-Riffraf

Now we need to apply pr.preproc only on the mono files so let us create a new list filenames_1 as follows

In [22]:
import re

In [23]:
filenames_1 = []
dirnames1 = []
rootdir = './input_exp/converted/'
root = './input_exp/converted/'
for root,dirs,files in os.walk(root):
    for wav_file in files:
        if wav_file.endswith("_mono.wav"):
            filenames_1.append((os.path.join(root, wav_file)))
            dirnames1.append(re.sub(rootdir,"",root))
            print((re.sub(rootdir,"",root)))

Bent-Beak-Riffraff_call
Bent-Beak-Riffraff_call
Bent-Beak-Riffraff_call
Bent-Beak-Riffraff_call
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffraff_song
Bent-Beak-Riffra

In [24]:
filenames_1

['./input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-102830_call_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-14774_call_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-20422_call_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_call\\Bent-Beak-Riffraff-63312_call_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103177_song_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103178_song_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-103181_song_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-106265_song_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-112603_song_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-116198_song_mono.wav',
 './input_exp/converted/Bent-Beak-Riffraff_song\\Bent-Beak-Riffraff-118831_song_mono.wav',
 '

In [16]:
dirnames1

['Bent-Beak-Riffraff_call',
 'Bent-Beak-Riffraff_call',
 'Bent-Beak-Riffraff_call',
 'Bent-Beak-Riffraff_call',
 'Bent-Beak-Riffraff_call',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff_song',
 'Bent-Beak-Riffraff

In [14]:
len(filenames_1) ##here i took only the mono files

1935

In [27]:
for filename,dirname in zip(filenames_1,dirnames1):   ###and therefore i can split this mono_files using pr.preprocess function
    pr.preprocess_sound_file(filename, './trial_converted/input_exp/class_dir/', './trial_converted/input_exp/noise_dir/', 3)       

[ -255 -1209  -613 ... -7470 -7430 -7904]
[-1  0  0 ...  0  0  0]
[ 0  0  0 ... -1 -1 -3]
[-820 -144 -153 ... 9824 7438 7708]
[  -1    0    0 ... -117 -207 -132]
[-1  0  0 ...  0  0  0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[-2176 -2059 -2014 ... -1812 -2001 -2220]
[0 0 0 ... 0 0 1]
[0 0 0 ... 0 0 0]
[-1  0  0 ...  0  0  0]
[-1  0  0 ...  0  0 -1]
[ 0  0  0 ...  0 -1  1]
[ 0  0  0 ... 14 16 12]
[  0   0   0 ... -11 -21   6]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[  0   0   0 ...  18   6 -24]
[   0    0    0 ...  983  383 -914]
[0 0 0 ... 5 0 1]
[-1  0  0 ... 19 16  1]
[0 0 0 ... 0 0 0]


KeyboardInterrupt: 